spring:
  application:
         name: kafka-producer-springboot
  kafka:
    producer:
      bootstrap-servers:
        - localhost:9092
server:
  port: 9191
  servlet:
    context-path: /producer-app

